### ISSUE TITLE
node active 状态判断

### ISSUE THREAD

**Issue by ChrisFan** [RaoHai/fringing#7]
![fringing](https://cloud.githubusercontent.com/assets/897640/19504644/72984296-95ee-11e6-83c9-4d918120fd73.gif)

目前看到的情况是未选中 `dataflow` 节点之前，hover 不会触发 active;
选中 `dataflow` 节点之后，该节点变成 active 状态，但是 hover 其他节点也会触发 active 状态

**Comment by ChrisFan** [comment]
@jaredleechn 关注下

**Comment by jaredleechn** [comment]
这个只是样式上发生了变化，加了 active 这个 class，但是在 store 上 active 的节点并没有发生变化，可以通过 onActiveNodesChange 来打印下

@RaoHai 这个命名确实有点不合适，用 hover 做样式处理可以吗？

**Comment by RaoHai** [comment]
好象是 targetNode 影响了 active 的逻辑。
